name: Build and Run Docker Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for Frontend
      run: |
        cd chatAppFrontend
        docker build -t frontend .

    - name: Build Docker image for Backend
      run: |
        cd chatAppBackend
        docker build -t backend .

    - name: Build Docker image for Auth Server
      run: |
        cd chatAppAuthserver
        docker build -t authserver .

    - name: Run Docker Compose
      run: |
        docker-compose up -d

    - name: Check running containers
      run: |
        docker ps
